version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: shop-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: userDB
      POSTGRES_USER: shopuser
      POSTGRES_PASSWORD: shoppass
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  mongodb:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: always

  auth-service:
    build:
      context: authservice
      dockerfile: Dockerfile
    container_name: auth-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/userDB
      SPRING_DATASOURCE_USERNAME: shopuser
      SPRING_DATASOURCE_PASSWORD: shoppass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8081"
    restart: always

  api-gateway:
    build:
      context: apigateway
      dockerfile: Dockerfile
    container_name: api-gateway
    depends_on:
      - auth-service
    environment:
      AUTH_SERVICE_URL: http://auth-service:8081
      NOTIFICATION_SERVICE_URL: http://notification-service:8083
    ports:
      - "8080:8080"
    restart: always

  notification-service:
    build:
      context: notificationservice
      dockerfile: Dockerfile
    container_name: notification-service
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/notificationDB
      SPRING_MAIL_USERNAME: notification.veedev@gmail.com
      SPRING_MAIL_PASSWORD: otfm qmpu uexj rjni
    ports:
      - "8083:8083"
    restart: always

volumes:
  pgdata:
  mongodata:
