version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: shop-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: userDB
      POSTGRES_USER: shopuser
      POSTGRES_PASSWORD: shoppass
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  mongodb:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: always

  traefik:
    image: traefik:v2.11.25
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=tishko.artyr@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    ports:
      - "80:80"
      - "443:443"
    restart: always

  auth-service:
    build:
      context: authservice
      dockerfile: Dockerfile
    container_name: auth-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/userDB
      SPRING_DATASOURCE_USERNAME: shopuser
      SPRING_DATASOURCE_PASSWORD: shoppass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8081
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth-retail.duckdns.org`)"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.tls.certresolver=myresolver"
      - "traefik.http.services.auth.loadbalancer.server.port=8081"
    ports:
      - "8081:8081"
    restart: always

  api-gateway:
    build:
      context: apigateway
      dockerfile: Dockerfile
    container_name: api-gateway
    depends_on:
      - auth-service
    environment:
      AUTH_SERVICE_URL: http://auth-service:8081
      NOTIFICATION_SERVICE_URL: http://notification-service:8083
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=Host(`gw-retail.duckdns.org`)"
      - "traefik.http.routers.gateway.entrypoints=websecure"
      - "traefik.http.routers.gateway.tls.certresolver=myresolver"
      - "traefik.http.services.gateway.loadbalancer.server.port=8080"
    ports:
      - "8080:8080"
    restart: always

  notification-service:
    build:
      context: notificationservice
      dockerfile: Dockerfile
    container_name: notification-service
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/notificationDB
      SPRING_MAIL_USERNAME: notification.veedev@gmail.com
      SPRING_MAIL_PASSWORD: otfm qmpu uexj rjni
      SERVER_PORT: 8083
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notification.rule=Host(`notify-retail.duckdns.org`)"
      - "traefik.http.routers.notification.entrypoints=websecure"
      - "traefik.http.routers.notification.tls.certresolver=myresolver"
      - "traefik.http.services.notification.loadbalancer.server.port=8083"
    ports:
      - "8083:8083"
    restart: always

volumes:
  pgdata:
  mongodata:
