version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: shop-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: userDB
      POSTGRES_USER: shopuser
      POSTGRES_PASSWORD: shoppass
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  auth-service:
    build:
      context: authservice
      dockerfile: Dockerfile
    container_name: auth-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/userDB
      SPRING_DATASOURCE_USERNAME: shopuser
      SPRING_DATASOURCE_PASSWORD: shoppass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8081"
    restart: always

  api-gateway:
    build:
      context: apigateway
      dockerfile: Dockerfile
    container_name: api-gateway
    depends_on:
      - auth-service
    environment:
      AUTH_SERVICE_URL: http://auth-service:8081
    ports:
      - "8080:8080"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - certbot-www:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api-gateway
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 1; done'"
    restart: always

volumes:
  pgdata:
  certbot-etc:
  certbot-www: