spring.application.name=notificationservice

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}

springdoc.swagger-ui.url=${SPRINGDOC_SWAGGER_UI_URL}

notification.token.secret=${NOTIFICATION_TOKEN_SECRET}
notification.email.base.unsub-url=${NOTIFICATION_EMAIL_BASE_UNSUB_URL}
notification.email.base.forgotpassword-url=${NOTIFICATION_EMAIL_BASE_FORGOT_PASSWORD_URL}
secret.key=${SECRET_KEY}

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}

server.port=${SERVER_PORT:8083}