name: Deploy to Google VM

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload project files to VM via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_KEY }}
          source: "."
          target: "/home/${{ secrets.VM_USER }}/Backend-Shop"

      - name: Prepare letsencrypt folder and permissions
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_KEY }}
          script: |
            cd /home/${{ secrets.VM_USER }}/Backend-Shop

            mkdir -p ./letsencrypt

            if [ ! -f ./letsencrypt/acme.json ]; then
              touch ./letsencrypt/acme.json
              echo '{}' > ./letsencrypt/acme.json
            fi

            chmod 600 ./letsencrypt/acme.json

      - name: Run docker-compose up with Traefik and other services
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_KEY }}
          script: |
            cd /home/${{ secrets.VM_USER }}/Backend-Shop

            docker-compose up --build -d traefik auth-service api-gateway notification-service product-service
